# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7d016dcf69b70b1454a032e83837e1e7"
application_url = "http://localhost:5000/"
embedded = false
name = "Multi-Vendor-Pro"
handle = "multi-vendor-pro"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_all_orders,read_orders,write_orders,read_customers,write_inventory,read_locations"


[auth]
redirect_urls = [
  "http://localhost:5000/auth/callback",
  "http://localhost:5000/auth/shopify/callback",
  "http://localhost:5000/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
